env:
  browser: true
  es6: true
extends:
  - ./eslint-config.yaml
  - plugin:react/recommended
settings:
  react:
    version: 16.6.0
rules:
  no-undef: off
  no-unused-vars: off
  no-use-before-define: off
