parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  es6: true
rules:
  eqeqeq: warn
  for-direction: error
  getter-return: error
  no-compare-neg-zero: warn
  no-cond-assign: error
  no-console: warn
  no-constant-condition: error
  no-debugger: warn
  no-dupe-args: error
  no-dupe-keys: warn
  no-duplicate-case: error
  no-empty: warn
  no-empty-character-class: warn
  no-ex-assign: warn
  no-extra-boolean-cast: warn
  no-extra-semi: warn
  no-func-assign: error
  no-inner-declarations: warn
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-obj-calls: error
  no-regex-spaces: warn
  no-sparse-arrays: error
  no-template-curly-in-string: warn
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  use-isnan: warn
  valid-jsdoc: warn
  valid-typeof: error
  constructor-super: error
  no-class-assign: error
  no-const-assign: error
  no-dupe-class-members: error
  no-duplicate-imports: warn
  no-new-symbol: error
  no-this-before-super: error
  no-useless-computed-key: warn
  no-useless-constructor: warn
  no-useless-rename: warn
  no-var: warn
  prefer-const: warn
  prefer-destructuring: warn
  prefer-numeric-literals: warn
  prefer-rest-params: warn
  prefer-spread: warn
  prefer-template: warn
  require-yield: error
  symbol-description: warn
  no-buffer-constructor: warn
  no-mixed-requires: warn
  no-new-require: warn
  no-path-concat: warn
  no-process-exit: warn
  no-delete-var: error
  no-label-var: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-undef: error
  no-undef-init: warn
  no-unused-vars: warn
  no-use-before-define: error
  strict: warn
  accessor-pairs: warn
  array-callback-return: error
  block-scoped-var: error
  class-methods-use-this: error
  curly: warn
  dot-location:
    - warn
    - property
  dot-notation: warn
  no-alert: warn
  no-caller: error
  no-case-declarations: error
  no-div-regex: error
  no-else-return: warn
  no-empty-function: warn
  no-empty-pattern: error
  no-eq-null: warn
  no-eval: error
  no-extra-bind: warn
  no-extra-label: warn
  no-fallthrough: warn
  no-floating-decimal: warn
  no-global-assign: warn
  no-implicit-coercion: warn
  no-implied-eval: warn
  no-iterator: warn
  no-lone-blocks: warn
  no-multi-spaces: warn
  no-new-func: error
  no-new-wrappers: warn
  no-octal: warn
  no-octal-escape: warn
  no-return-assign: warn
  no-script-url: error
  no-self-assign: warn
  no-self-compare: warn
  no-throw-literal: warn
  no-unmodified-loop-condition: warn
  no-unused-expressions: warn
  no-unused-labels: warn
  no-useless-concat: warn
  no-useless-return: warn
  no-void: warn
  no-with: error
  require-await: warn
  complexity: warn
