export default new Map([
  [`ActionBar`, [
    `actionBarDefault`,
    `actionBarDefaultIcon`,
    `actionBarDefaultTitle`,
    `avatar_backgroundRed`,
    `avatar_text`,
    `chats_date`,
    `chats_message`,
    `chats_name`,
    `chats_sentCheck`,
    `windowBackgroundWhite`,
  ]],
  [`AttachmentsBots`, [
    `dialogBackground`,
    `dialogBackgroundGray`,
    `chat_attachFileBackground`,
    `chat_attachFileIcon`,
    `chat_attachContactBackground`,
    `chat_attachContactIcon`,
    `chat_attachLocationBackground`,
    `chat_attachLocationIcon`,
    `chat_attachSendBackground`,
    `chat_attachSendIcon`,
    `chat_attachHideBackground`,
    `chat_attachHideIcon`,
    `dialogTextGray2`,
  ]],
  [`AttachmentsGallery`, [
    `dialogCameraIcon`,
    `dialogGrayLine`,
    `chat_attachCameraIcon1`,
    `chat_attachCameraIcon2`,
    `chat_attachCameraIcon6`,
    `chat_attachCameraIcon3`,
    `chat_attachCameraIcon4`,
    `chat_attachCameraIcon5`,
    `chat_attachGalleryBackground`,
    `chat_attachGalleryIcon`,
    `chat_attachVideoBackground`,
    `chat_attachVideoIcon`,
    `chat_attachAudioBackground`,
    `chat_attachAudioIcon`,
  ]],
  [`ChatsMenu`, [
    `chats_menuName`,
    `chats_menuPhone`,
    `chats_menuTopShadow`,
  ]],
  [`Checkboxes`, [
    `avatar_backgroundBlue`,
    `checkboxSquareDisabled`,
    `checkboxSquareCheck`,
    `checkboxSquareBackground`,
    `checkboxSquareCheck`,
    `checkboxSquareUnchecked`,
  ]],
  [`Checkout`, [
    `divider`,
    `windowBackgroundWhiteBlackText`,
    `windowBackgroundWhiteBlueText6`,
  ]],
  [`Contacts`, [
    `avatar_backgroundCyan`,
    `avatar_backgroundPink`,
    `graySection`,
    `key_graySectionText`,
  ]],
  [`CreateChannelScreenBottom`, [
    `windowBackgroundWhiteBlueText5`,
    `windowBackgroundWhiteGrayText2`,
  ]],
  [`CreateChannelScreenTop`, [
    `actionBarWhiteSelector`,
  ]],
  [`DeleteGroup`, [
    `windowBackgroundGray`,
    `windowBackgroundGrayShadow`,
    `windowBackgroundWhiteRedText5`,
    `windowBackgroundWhiteGrayText4`,
  ]],
  [`FieldPlaceholder`, [
    `windowBackgroundWhiteHintText`,
    `windowBackgroundWhiteInputFieldActivated`,
  ]],
  [`GlobalSearch`, [
    `windowBackgroundWhiteGrayText3`,
    `windowBackgroundWhiteBlueText3`,
    `chats_verifiedBackground`,
    `chats_nameIcon`,
    `chats_verifiedCheck`,
  ]],
  [`GroupMembersList`, [
    `windowBackgroundWhiteBlueText`,
    `windowBackgroundWhiteGrayText`,
    `windowBackgroundWhiteGrayIcon`,
    `profile_creatorIcon`,
    `profile_adminIcon`,
  ]],
  [`GroupsPrivacy`, [
    `radioBackground`,
    `radioBackgroundChecked`,
    `actionBarDefaultSelector`,
  ]],
  [`InviteButton`, [
    `groupcreate_checkboxCheck`,
    `groupcreate_checkbox`,
    `groupcreate_offlineText`,
    `contacts_inviteBackground`,
    `contacts_inviteText`,
  ]],
  [`InviteSearch`, [
    `actionBarDefaultSearchPlaceholder`,
  ]],
  [`ListSelector`, [
    `chats_menuBackground`,
    `chats_menuItemIcon`,
    `chats_menuItemText`,
    `listSelectorSDK21`,
  ]],
  [`MutedChat`, [
    `avatar_backgroundViolet`,
    `chats_actionMessage`,
    `chats_muteIcon`,
    `chats_unreadCounterMuted`,
  ]],
  [`NewGroup`, [
    `groupcreate_hintText`,
    `fastScrollInactive`,
  ]],
  [`NewGroupSelections`, [
    `groupcreate_spanBackground`,
    `groupcreate_spanText`,
    `avatar_backgroundGroupCreateSpanBlue`,
    `groupcreate_cursor`,
    `groupcreate_onlineText`,
    `fastScrollActive`,
    `fastScrollText`,
    `actionBarDefaultSubtitle`,
  ]],
  [`NoSearchResults`, [
    `emptyListPlaceholder`,
    `actionBarDefaultSearch`,
  ]],
  [`PinnedChat`, [
    `chats_pinnedIcon`,
    `chats_pinnedOverlay`,
  ]],
  [`PlayerActionBar`, [
    `player_actionBar`,
    `player_actionBarItems`,
    `player_actionBarTitle`,
    `player_actionBarSubtitle`,
    `player_actionBarTop`,
  ]],
  [`PlayerBackground`, [
    `player_button`,
    `player_buttonActive`,
    `player_placeholder`,
    `player_progress`,
    `player_progressBackground`,
    `player_time`,
    `player_background`,
    `player_placeholderBackground`,
  ]],
  [`Search`, [
    `windowBackgroundWhiteBlueText4`,
    `groupcreate_sectionText`,
    `groupcreate_sectionShadow`,
  ]],
  [`SecretChat`, [
    `avatar_backgroundGreen`,
    `chats_secretIcon`,
    `chats_secretName`,
  ]],
  [`SettingsSupport`, [
    `windowBackgroundWhiteBlueHeader`,
    `windowBackgroundWhiteGrayText5`,
  ]],
  [`ThemeItem`, [
    `featuredStickers_addedIcon`,
    `stickers_menuSelector`,
    `stickers_menu`,
  ]],
  [`UnreadChat`, [
    `avatar_backgroundOrange`,
    `chats_unreadCounter`,
    `chats_unreadCounterText`,
  ]],
  [`UsernameAvailable`, [
    `windowBackgroundWhiteGreenText`,
  ]],
  [`UsernameUnavailable`, [
    `windowBackgroundWhiteRedText4`,
    `windowBackgroundWhiteGrayText8`,
    `windowBackgroundWhiteLinkSelection`,
    `windowBackgroundWhiteLinkText`,
  ]],
]);
