const previewsMap = {
  /* eslint-disable camelcase */
  actionBarDefault: `actionBarDefault`,
  actionBarDefaultIcon: `actionBarDefault`,
  actionBarDefaultTitle: `actionBarDefault`,
  actionBarWhiteSelector: `actionBarWhiteSelector`,
  avatar_backgroundOrange: `chats_unreadCounter`,
  avatar_backgroundGreen: `chats_secretName`,
  avatar_backgroundRed: `actionBarDefault`,
  avatar_backgroundViolet: `chats_actionMessage`,
  avatar_text: `actionBarDefault`,
  chats_actionMessage: `chats_actionMessage`,
  chats_date: `actionBarDefault`,
  chats_menuBackground: `listSelectorSDK21`,
  chats_menuItemIcon: `listSelectorSDK21`,
  chats_menuItemText: `listSelectorSDK21`,
  chats_menuName: `chats_menuName`,
  chats_menuPhone: `chats_menuName`,
  chats_menuTopShadow: `chats_menuName`,
  chats_message: `actionBarDefault`,
  chats_muteIcon: `chats_actionMessage`,
  chats_name: `actionBarDefault`,
  chats_pinnedIcon: `chats_pinnedIcon`,
  chats_pinnedOverlay: `chats_pinnedIcon`,
  chats_secretIcon: `chats_secretName`,
  chats_secretName: `chats_secretName`,
  chats_sentCheck: `actionBarDefault`,
  chats_unreadCounter: `chats_unreadCounter`,
  chats_unreadCounterMuted: `chats_actionMessage`,
  chats_unreadCounterText: `chats_unreadCounter`,
  divider: `windowBackgroundWhiteBlueText6`,
  listSelectorSDK21: `listSelectorSDK21`,
  player_actionBar: `player_actionBar`,
  player_actionBarItems: `player_actionBar`,
  player_actionBarTitle: `player_actionBar`,
  player_actionBarSubtitle: `player_actionBar`,
  player_actionBarTop: `player_actionBar`,
  player_button: `player_background`,
  player_buttonActive: `player_background`,
  player_placeholder: `player_background`,
  player_progress: `player_background`,
  player_progressBackground: `player_background`,
  player_time: `player_background`,
  player_background: `player_background`,
  player_placeholderBackground: `player_background`,
  windowBackgroundWhite: `actionBarDefault`,
  windowBackgroundWhiteBlackText: `windowBackgroundWhiteBlueText6`,
  windowBackgroundWhiteBlueText5: `windowBackgroundWhiteBlueText5`,
  windowBackgroundWhiteBlueText6: `windowBackgroundWhiteBlueText6`,
  windowBackgroundWhiteGrayText2: `windowBackgroundWhiteBlueText5`,
  /* eslint-enable camelcase */
};

export default previewsMap;
